name: flutter_clean_architecture_example
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  auto_route: ^11.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  email_validator: ^3.0.0
  envied: ^1.3.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  flutter_secure_storage: ^10.0.0
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  meta: ^1.17.0
  retrofit: ^4.9.2
  riverpod_annotation: ^4.0.0
  uuid: ^4.5.2

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  drift_dev: ^2.30.0
  envied_generator: ^1.3.2
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  lint: ^2.8.0
  retrofit_generator: ^10.2.1
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.0

flutter:
  uses-material-design: true
